/**
 * Medical French vocabulary for phonetic correction.
 *
 * These are the CORRECT spellings of medical terms. The phonetic
 * matcher uses this list to find the closest match for unknown
 * words in STT output.
 *
 * Sources: MeSH French, Compendium.ch, Swiss medical terminology.
 */

export const MEDICAL_VOCAB: string[] = [
  // ── Drugs & Medications ──
  "pipéracilline", "tazobactam", "noradrénaline", "adrénaline", "vasopressine",
  "amiodarone", "metformine", "ceftriaxone", "insuline", "héparine",
  "morphine", "paracétamol", "ibuprofène", "oméprazole", "pantoprazole",
  "furosémide", "propofol", "midazolam", "fentanyl", "kétamine",
  "vancomycine", "méropénème", "ciprofloxacine", "amoxicilline", "clindamycine",
  "métronidazole", "fluconazole", "acétylcystéine", "sandostatine", "dobutamine",
  "dopamine", "atropine", "digoxine", "warfarine", "rivaroxaban",
  "énoxaparine", "prednisone", "dexaméthasone", "hydrocortisone", "lévothyroxine",
  "méthotrexate", "azathioprine", "ciclosporine", "tacrolimus", "mycophénolate",
  "rituximab", "infliximab", "adalimumab", "étanercept", "tocilizumab",
  "nitroglycérine", "nitroprussiate", "milrinone", "lévosimendan", "phényléphrine",
  "éphédrine", "néostigmine", "sugammadex", "rocuronium", "cisatracurium",
  "thiopental", "étomidate", "dexmédétomidine", "clonidine", "gabapentine",
  "prégabaline", "tramadol", "oxycodone", "hydromorphone", "naloxone",
  "flumazénil", "protamine", "acide tranexamique", "fibrinogène", "facteur",
  "immunoglobulines", "albumine", "cristalloïdes", "colloïdes", "bicarbonate",
  "sodium", "potassium", "calcium", "magnésium", "phosphore",
  "mannitol", "acétazolamide", "spironolactone", "hydrochlorothiazide",
  "ramipril", "énalapril", "lisinopril", "losartan", "valsartan",
  "amlodipine", "nifédipine", "diltiazem", "vérapamil", "métoprolol",
  "bisoprolol", "carvédilol", "labétalol", "esmolol", "lidocaïne",
  "atorvastatine", "rosuvastatine", "ézétimibe", "clopidogrel", "ticagrélor",
  "prasugrel", "aspirine", "dabigatran", "apixaban", "édoxaban",
  "fondaparinux", "altéplase", "ténectéplase", "streptokinase",
  "pantoprazole", "ésoméprazole", "lansoprazole", "ranitidine",
  "ondansétron", "métoclopramide", "dompéridone", "lopéramide",
  "lactulose", "macrogol", "mésalazine", "sulfasalazine",
  "lévofloxacine", "moxifloxacine", "gentamicine", "tobramycine", "amikacine",
  "cotrimoxazole", "triméthoprime", "nitrofurantoïne", "fosfomycine",
  "amphotéricine", "caspofungine", "voriconazole", "posaconazole",
  "aciclovir", "valaciclovir", "ganciclovir", "oseltamivir",
  "hydroxychloroquine", "colchicine", "allopurinol", "fébuxostat",

  // ── Medical Conditions ──
  "hémodynamique", "hémodynamiquement", "pneumocoque", "insuffisance",
  "cardiogène", "néphrotique", "hépatomégalie", "septicémie", "bactériémie",
  "pneumonie", "embolie", "thrombose", "fibrillation", "auriculaire",
  "tachycardie", "bradycardie", "hypotension", "hypertension",
  "hyperkaliémie", "hypokaliémie", "hyponatrémie", "hypernatrémie",
  "acidose", "alcalose", "métabolique", "respiratoire",
  "rhabdomyolyse", "pancréatite", "cholécystite", "appendicite",
  "péritonite", "méningite", "endocardite", "péricardite", "myocardite",
  "ischémie", "infarctus", "anévrisme", "dissection", "hémorragie",
  "hémostase", "coagulopathie", "thrombopénie", "leucocytose", "anémie",
  "diabète", "hypothyroïdie", "hyperthyroïdie", "cirrhose",
  "encéphalopathie", "neuropathie", "myopathie", "auto-immun",
  "artérielle", "ventriculaire", "supraventriculaire", "atriale",
  "ischémique", "hémorragique", "thrombotique", "embolique",
  "septique", "cardiaque", "respiratoire", "rénale", "hépatique",
  "neurologique", "infectieuse", "inflammatoire", "dégénérative",
  "aiguë", "chronique", "décompensée", "compensée",
  "pulmonaire", "bilatérale", "unilatérale", "diffuse", "focale",
  "systolique", "diastolique", "mixte",
  "pneumothorax", "hémothorax", "épanchement", "ascite",
  "oedème", "cyanose", "dyspnée", "orthopnée", "tachypnée",
  "oligurie", "anurie", "polyurie", "hématurie", "protéinurie",
  "hémoptysie", "méléna", "hématémèse", "rectorragie",

  // ── Anatomy ──
  "cathéter", "abdomen", "thorax", "péritoine", "médiastin",
  "péricarde", "myocarde", "endocarde", "aorte", "artère", "veine",
  "bronche", "alvéole", "parenchyme", "mésentère", "épigastre",
  "hypochondre", "rétropéritoine", "duodénum", "jéjunum", "iléon",
  "côlon", "rectum", "oesophage", "estomac", "pancréas",
  "vésicule", "cholédoque", "uretère", "urètre", "vessie",
  "rein", "foie", "rate", "surrénale", "thyroïde",
  "cerveau", "cervelet", "tronc cérébral", "moelle épinière",
  "diaphragme", "plèvre", "trachée", "larynx", "pharynx",
  "fémur", "tibia", "péroné", "humérus", "radius", "cubitus",
  "vertèbre", "sacrum", "coccyx", "sternum", "clavicule",

  // ── Procedures ──
  "dialyse", "hémodialyse", "hémofiltration", "plasmaphérèse",
  "intubation", "extubation", "trachéotomie", "trachéostomie",
  "ventilation", "oxygénothérapie", "antibiothérapie", "anticoagulation",
  "thrombolyse", "angioplastie", "endoscopie", "coloscopie", "gastroscopie",
  "échographie", "tomodensitométrie", "radiographie", "scanner",
  "transfusion", "ponction", "biopsie", "laparotomie", "thoracotomie",
  "drainage", "suture", "réduction", "ostéosynthèse",
  "coronarographie", "artériographie", "phlébographie",
  "électrocardiogramme", "échocardiographie", "holter",
  "électroencéphalogramme", "ponction lombaire",
  "cathétérisme", "pacemaker", "défibrillateur",
  "chimiothérapie", "radiothérapie", "immunothérapie",

  // ── Lab Values ──
  "hémoglobine", "hématocrite", "leucocytes", "thrombocytes", "plaquettes",
  "créatinine", "bilirubine", "transaminases", "troponine", "procalcitonine",
  "lactate", "glycémie", "natrémie", "kaliémie", "calcémie",
  "phosphatémie", "magnésémie", "albuminémie", "protéinurie",
  "gazométrie", "coagulation", "fibrinogène", "D-dimères",
  "hémoglobine glyquée", "HbA1c", "TSH", "T3", "T4",
  "ferritine", "transferrine", "vitamine", "folate",
  "CRP", "VS", "PCT", "BNP", "NT-proBNP",
  "ASAT", "ALAT", "GGT", "phosphatases alcalines",
  "LDH", "CPK", "lipase", "amylase",
  "INR", "TP", "TCA", "fibrinogène", "antithrombine",

  // ── Clinical Terms ──
  "volémique", "vasoactif", "vasoactifs", "vasoactives",
  "aminergique", "inotrope", "chronotrope", "lusitrope",
  "vasoplégie", "tamponnade", "choc", "défaillance",
  "sédation", "curarisation", "analgésie", "anesthésie",
  "catécholamines", "vasopresseur", "inotropes",
  "réanimation", "soins intensifs", "monitorage", "sevrage",
  "pronostic", "pronostication", "récupération",

  // ── Microbiology ──
  "Pseudomonas", "aeruginosa", "Staphylococcus", "aureus",
  "Escherichia", "coli", "Klebsiella", "pneumoniae",
  "Enterococcus", "faecalis", "faecium",
  "Candida", "albicans", "Aspergillus", "fumigatus",
  "Streptococcus", "pneumoniae", "pyogenes",
  "Clostridium", "difficile", "Clostridioides",
  "Acinetobacter", "baumannii", "Serratia", "marcescens",
  "Proteus", "mirabilis", "Enterobacter", "cloacae",
  "Haemophilus", "influenzae", "Neisseria", "meningitidis",
  "méticilline", "SARM", "BLSE", "carbapénémase",
  "bactérie", "virus", "champignon", "parasite",
  "hémoculture", "uroculture", "coproculture",
  "antibiogramme", "CMI", "résistance", "sensibilité",
];
